# SPDX-License-Identifier: CC0-1.0

name: Lint

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.cff"
      - "**.json"
      - "**.md"
      - "**.txt"
      - "**.yml"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.cff"
      - "**.json"
      - "**.md"
      - "**.txt"
      - "**.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev,eval]'
      - name: Analysing the code with Pylint
        run: |
          pylint src tests
