# SPDX-License-Identifier: CC0-1.0

name: Pylint

on:
  pull_request:
    paths:
    - "*.py"
  push:
    paths:
    - "*.py"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  #v4.2.2
    - name: Set up Python 3.12
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  #v5.3.0
      with:
        python-version: "3.12"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-eval.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
