# SPDX-License-Identifier: CC0-1.0

name: Validate SBOM

on:
  pull_request:
    paths:
      - "*.spdx3.json"
  push:
    paths:
      - "*.spdx3.json"

jobs:
  validate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 #v6.2.0
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - name: Install Python dependencies
        run: |
          python3 -m pip install check-jsonschema==0.37.1 pyshacl==0.31.0 spdx3-validate==0.0.5
      - name: Check examples
        run: |
          ./tools/validate.sh --check-all
