# SPDX-License-Identifier: CC0-1.0

on:
  pull_request:
    paths:
      - '*.spdx3.json'
  push:
    paths:
      - '*.spdx3.json'
jobs:
  validate-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  #v4.1.7
      - name: Install Python dependencies
        run: |
          python3 -m pip install check-jsonschema==0.29.2 pyshacl==0.26.0 spdx3-validate==0.0.2
      - name: Check examples
        run: |
          ./tools/validate.sh --check-all
